-- NO MIGRATION v2 -> v3
--
-- v3 is a rebuild, not a migration, so this file is deliberately empty of
-- statements and `migrate.py` refuses before it would ever be read.

-- The previous migration is still in the history:
--     git log -p odyn/latest.sql
--
-- WHY THERE IS NO MIGRATION:
-- - `sessions` is a new level above `experiments`, and which experiments share
--   a session can only be guessed from folder names for data already ingested.
-- - `acquisitions` loses its sync-derived columns to `acquisition_sync`, whose
--   rows need the sync H5 re-read to be filled honestly.
-- - `method_calls` gains `user`, `module` and `code`. Those values do not exist
--   for calls already recorded, so any migration would have to invent values.
--
-- WHAT TO DO INSTEAD:
-- Start a new database (a project database is the usual way,
-- `Database(main_folder, project=...)`) and ingest into it. The old database
-- stays readable with the older tagged release, which is why that tag exists.
